[tool.kedro]
package_name = "dados_bcb"
project_name = "Dados BCB"
kedro_init_version = "0.18.6"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/dados_bcb -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
